name: DEFAULT
on: [workflow_dispatch]
jobs:
  pull_and_build:
    runs-on: windows

    steps:
      name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.PRIVATE_KEY}}
        port: 22
        script: |
          cd ~/projets/demo1/marc
          pwd
          git pull origin devops
          git status
          npm install
          npm run build
          pm2 start pm2.config.js